name: Update Ratings

on:
  push:
    branches:
      - main

jobs:
  update-ratings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

      - name: Install Python Dependencies
        run: pip install fire requests python-dotenv tqdm

      - name: Copy Secrets
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Fetch Ratings
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",target=/mnt/output tachyorca/imdb_user_crawler ratings -o /mnt/output/yms_ratings.json

      - name: Run Update Script
        run: |
          python scripts/update_ratings.py assets/YMS_ratings.json yms_ratings.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'tachyon-orca'
          git config --global user.email '152846110+tachyon-orca@users.noreply.github.com'
          git commit -a -m "Update ratings"
          git push
